### ISSUE TITLE
How to compare Enumerations

### ISSUE THREAD

**Issue by ithielnor** [jwaliszko/ExpressiveAnnotations#10]
I have a lot of RequiredIf attributes with enum Target values. Which is the correct way to write these in 2.0?

```
[RequiredIf("WithholdingType == " + (int)WithholdingType.FederalRateSchedule)]
```

OR

```
[RequiredIf("WithholdingType == " + WithholdingType.FederalRateSchedule)]
```

**Comment by HydrateEfficiently** [comment]
How can we do this for the client side?

I want to validate that my value is equal to an enum value, which is an integer in Javascript.

Instead I get:

System.ComponentModel.DataAnnotations.ValidationException: AssertThatValidator: validation applied to LastSabbaticalStatus field failed. ---> System.InvalidOperationException: Any naming collisions cannot be accepted at client side - LastSabbaticalStatus part at level 0 is ambiguous.

**Comment by JaroslawWaliszko** [comment]
@HydrateEfficiently (I know you've figured out how to solve your issue that's why the comment is removed now, nevertheless I'm answering just to give some explanation)

I'm writing regarding this exception you've asked about: 

> System.ComponentModel.DataAnnotations.ValidationException: AssertThatValidator: validation applied to LastSabbaticalStatus field  failed. ---> System.InvalidOperationException: Any naming collisions cannot be accepted at client side - LastSabbaticalStatus part at level 0 is ambiguous.

You have this issue because your field name is exactly the same as your enumeration type name, e.g.
```
public enum LastSabbaticalStatus
{
    Planned,
    Spontaneous		
}
	
[AssertThat("LastSabbaticalStatus == LastSabbaticalStatus.Planned")]
public int LastSabbaticalStatus { get; set; }
```
Normally at client side, based on fields and enums information sent by server, model object is constructed to satisfy expression evaluation engine. Unfortunately an ambiguity would appear in your situation. Firstly, model object would be constructed based on current field value, e.g.
```
{ 
    LastSabbaticalStatus : 1 
}
```
Next, enum-like object would be created:
```
{ 
    LastSabbaticalStatus : 
    {
        Planned : 0
    }
}
```
The second object simply overwrites the first one, so evaluation of 
```
with (model) {
    eval(LastSabbaticalStatus == LastSabbaticalStatus.Planned)
    ...
} 
```
would be broken (i.e. *Uncaught ReferenceError: LastSabbaticalStatus is not defined*). 

Because of that, such a situation is detected as soon as possible by the server code (just after parser finishes decomposition of an expression) and proper exception is thrown, to avoid unexpected behaviours at client side (notice that if client validation is disabled, namely validators are not registered, exception is not thrown, because server code has much more context to handle such a situations properly).

**Comment by HydrateEfficiently** [comment]
@JaroslawWaliszko Yup, figured it out, thanks mate. It was just me being a dumb user. This is a fantastic library, will definitely be using again in future projects wherever there's validation to be done, and recommending it to all my peers. Thanks for all the hard work and great support.

**Comment by JaroslawWaliszko** [comment]
@HydrateEfficiently No problem. It's nice to hear that you find it useful. Regards.
