### ISSUE TITLE
Problem wit german letters ä,ö,ü

### ISSUE THREAD

**Issue by madrianr** [jwaliszko/ExpressiveAnnotations#100]
There is a problem with german letters ä,ö,ü in column names - see picture
i.e Column Name = Zustimmungserklärung

![error](https://cloud.githubusercontent.com/assets/10518186/12478551/cf8bcdd6-c035-11e5-814b-724dbeca65bb.PNG)

robert

**Comment by jwaliszko** [comment]
It's by design, currently only alphanumeric characters are allowed for func literals, see [readme](https://github.com/jwaliszko/ExpressiveAnnotations/tree/e90b6d291aea2a8ecf35a6bc42d1c847e232ba9e#implementation) and [code](https://github.com/jwaliszko/ExpressiveAnnotations/blob/e90b6d291aea2a8ecf35a6bc42d1c847e232ba9e/src/ExpressiveAnnotations/Analysis/Lexer.cs#L55).
Regards

**Comment by madrianr** [comment]
Is it possible to extend the solution to support these characters?

robert

**Comment by jwaliszko** [comment]
This is possible, but not in the scope for now. If this is to be implemented, not only these characters should be supported, but the whole set defined by [C# specification](https://msdn.microsoft.com/en-us/library/aa664670.aspx), or some slightly, yet reasonably, simplified subset (e.g. see also [this](http://stackoverflow.com/a/950651/270315), or [this](http://stackoverflow.com/a/4400503/270315) answer). Because only alphanumeric characters are supported, the current regex is simple and usage case is clearly defined. Also, if more characters is to be supported, the client-side should work with all of them as well.

**Comment by madrianr** [comment]
I think it is a important extension for all languages with special characters...

robert

**Comment by jwaliszko** [comment]
I do not agree actually it is that important. The code should be, at least in my humble opinion, most of the time written in English - unless you're writing code for yourself. 

Imagine e.g. this EA library is written in some other language, and due to that e.g. `AssertThat` attribute is defined not as `public class AssertThat { ... }`, but as e.g. `public class それをアサート { ... }`. I've picked up Japanese letters just as an example, because I've just started to learn this language (and I'd really love to master it some day!). Unless you know this beautiful language, the code is not really useful (at least not when it comes to push any contribution), because you could always decorate your model like that:
```
[それをアサート("your expression")]
public string SomeProperty { get; set; }
```
BTW: You can obviously use any characters in the string literals, e.g. "SomeProperty == 'äöüß'".

**Comment by madrianr** [comment]
OK - my problem is that in the underlaying database some fields are used with this "special" chars (not special für germans) and that is why I cannot use your library in that database...
robert

**Comment by jwaliszko** [comment]
Now it's clear, you've used some reverse engineering tool to generate code based on existing database schema.

**Comment by madrianr** [comment]
Yes and we have a lot of such DB's and the main CRM DB is that one which I have to migration from a Desktop App to a MVC App and there are a lot of Column names with ä,ü,ö...

**Comment by jwaliszko** [comment]
Unicode support added: https://github.com/jwaliszko/ExpressiveAnnotations/commit/1b5eb0d5cf47653222d3240d28b3c11bc8ba4d62.
