### ISSUE TITLE
WebAPI: RequiredIf throws NullReferenceException for properties with DisplayAttribute, where Name does not match property name

### ISSUE THREAD

**Issue by girtsl** [jwaliszko/ExpressiveAnnotations#118]
Here is a simplified class to reproduce the bug:

```
public class SampleModel
{
	[RequiredIf("true", ErrorMessage = "You must enter your first name")]
	[Display(Name = "First name")]
	public string FirstName { get; set; }
}
```

I traced it to `RequiredIfAttribute.IsValidInternal()` - `validationContext.MemberName` contains the display name "First name", which, of course, is not a property name and thus the `validationContext.ObjectType.GetProperty()` returns null.

Unfortunately I cannot offer a solution as I haven't dealt with MVC validation in depth.

P.S. This was introduced in 2.7.0, commit https://github.com/jwaliszko/ExpressiveAnnotations/commit/b4afd1eef0ef9b4a7d486081812ef8d1d3750b12

**Comment by jwaliszko** [comment]
Could you please provide some tiny sample for this to be reproduced? I have many properties with names containing spaces used across multiple tests and [no error is being thrown](https://ci.appveyor.com/project/jwaliszko/ExpressiveAnnotations/build/tests).

**Comment by girtsl** [comment]
My bad for not trying it out in an MVC application - I mostly work with WebApi. You are right, of course, in MVC it works as expected and `validationContext.MemberName` indeed contains the member's name.
I guess it must be a bug in WebAPI's model validator, which puts the DisplayName in MemberName. You can reproduce the issue with the class I posted above and this minimalistic API controller:
```
public class DefaultController : ApiController
    {
        [HttpPost]
        public IHttpActionResult Index(SampleModel model)
        {
            return Ok();
        }
    }
```

I see that this is not a bug with your lib, as you are targeting MVC, but it also stops your lib from being used in WebAPI projects. Which, prior to version 2.7.0, worked beautifully.

**Comment by jwaliszko** [comment]
Thanks for clarification. There were previously issues with this `MemberName` as well, i.e. 

* in MVC 4 `DataAnnotationsModelValidator::Validate()` method, there is no `MemberName` provided, only `DisplayName`:

 ```
ValidationContext context = new ValidationContext(container ?? Metadata.Model, null, null);
context.DisplayName = Metadata.GetDisplayName();
```
that's why I'm trying to retrieve this `MemberName` using `DisplayName` through reflection lookup for `Display` or `DisplayName` attributes. If I find any, I get the name of the decorated property which becomes the `MemberName`, i.e.
 ```
validationContext.MemberName = validationContext.MemberName
      ?? validationContext.ObjectType.GetMemberNameByDisplayName(validationContext.DisplayName);
```
I've just found an error here, because when there is no such an `Display` nor `Displayname` annotation, I end up with `null`. I've just added one single line, mainly `?? DisplayName`:
 ```
validationContext.MemberName = validationContext.MemberName
      ?? validationContext.ObjectType.GetMemberNameByDisplayName(validationContext.DisplayName)
      ?? DisplayName;
 ```
Why? From the dive into MVC source code:
 ```
public string GetDisplayName()
{
        return DisplayName ?? PropertyName ?? ModelType.Name;
}
```
I can see than when there is no `DisplayName` nor `Display` annotation, `DisplayName` property becomes the name of the property itself, so it works as expected:

* in MVC 5 situation is fixed - `MemberName` is there:

 ``` 
string memberName = Metadata.PropertyName ?? Metadata.ModelType.Name;
ValidationContext context = new ValidationContext(container ?? Metadata.Model)
{
        DisplayName = Metadata.GetDisplayName(),
        MemberName = memberName
};
```
* in WebAPI, from what you have expected, seems to exists yet another issue. If we have `DisplayName` in the place of `MemberName` we probably need to lookup for the name of the property in the same way, it's done for MVC 4 case, so will we end up with something like this...?
 ```
if( validationContext.MemberName != null) // hack for WebAPI, where `MemberName` is actually `DisplayName`
      validationContext.MemberName = validationContext.ObjectType.GetMemberNameByDisplayName(validationContext.MemberName)

validationContext.MemberName = validationContext.MemberName // hack for old MVC
      ?? validationContext.ObjectType.GetMemberNameByDisplayName(validationContext.DisplayName)
      ?? DisplayName;
```                               
Why `MemberName` is that important? It isn't actually but I need it because I introduced a safety check in case of improper applications of `RequiredIf` attributes for value types. I'd like it to prevent such mistakes for WebAPI users as well, that's why I'd like to avoid this:
 ```
protected override ValidationResult IsValidInternal(object value, ValidationContext validationContext)
{
        if (validationContext.MemberName != null)
        {
            // do the checks introduced in commit
            // https://github.com/jwaliszko/ExpressiveAnnotations/commit/b4afd1eef0ef9b4a7d486081812ef8d1d3750b12
        }
```
I need to think about this next hack i shown one step before.

**Comment by jwaliszko** [comment]
The following commit: https://github.com/jwaliszko/ExpressiveAnnotations/commit/44e2ab792d149abdfe6142a90c0cec84cc4b28a4, will most likely fix both problems mentioned in this topic.

**Comment by girtsl** [comment]
Yes, it fixes the issue(s). Thanks!
