### ISSUE TITLE
Add bower.json to support Bower

### ISSUE THREAD

**Issue by antonrademaker** [jwaliszko/ExpressiveAnnotations#124]
As the client side validation depends on some scripts, it should be nice to have install from Bower (http://bower.io/docs/creating-packages/)

**Comment by ruant** [comment]
PR: https://github.com/jwaliszko/ExpressiveAnnotations/pull/132

**Comment by jwaliszko** [comment]
@ruant, @antonrademaker : I have a question related to version numbers of bower.json (bower), and package.json (npm). 

Since these packages contain expressive.annotations.validate.js script only (as opposite to NuGet package, which in fact contains all 3 components - the script and 2 DLLs), shouldn't they reflect the version of the script file alone (currently it would be 2.6.8, instead the version of the entire product, i.e. 2.9.1)? 

Do you have any recommendations (pros/cons) regarding versioning in such a case?

**Comment by jwaliszko** [comment]
@ruant, you may take a look at this: https://github.com/bower/bower/issues/2367

**Comment by jwaliszko** [comment]
Closing for now, because Bower does not support mono repositories (at least for now). Separate distribution repository for the script component is something I prefer not to maintain, sorry.
