### ISSUE TITLE
Access parent object properties

### ISSUE THREAD

**Issue by sstanaland** [jwaliszko/ExpressiveAnnotations#156]
First off, I love your library.  I've tried several other MVC validation extensions and yours is by far the most flexible and it works.

Reading through the docs, I don't think this is possible, but I wanted to verify.

I have a scenario where I need to validate a child object property as required only if a Boolean property in the top level object is true.

The child object is a List property in the main object.

Any idea how I could handle this scenario?

Thanks
Scott

**Comment by jwaliszko** [comment]
Hi,
In this case you need to have a back reference to your parent model.
Otherwise there is no way to access it.

Some time ago [I've been looking for](http://stackoverflow.com/questions/18273278/declarative-conditional-validation-of-a-field-based-on-other-one-from-parent-mod) a way of handling such a requirement but without results.

**Comment by sstanaland** [comment]
That's what I thought.

Thanks for following up.

Scott
