### ISSUE TITLE
Hidden Input Dynamic

### ISSUE THREAD

**Issue by macfs36** [jwaliszko/ExpressiveAnnotations#161]
Is there any way to hide or disable a field based on another equal to the requiredif?

Thanks

**Comment by jwaliszko** [comment]
There is such a possibility, but not out of the box. You could make a use of [`eavalid`](https://github.com/jwaliszko/ExpressiveAnnotations/blob/master/README.md#is-there-any-event-raised-when-validation-is-done) event + some additional coding to achieve that. 

Instead of disabling non-required fields, some users prefer hiding, some other annotating with asterisk, etc. In the MVC sample I've provided examplary solution to such use cases. Take a look at *Home.cshtml* view - [`annotateRequiredFields()`](https://github.com/jwaliszko/ExpressiveAnnotations/blob/2846ae0b39ff2c2117a9fd0dd723cba6aa48ab7d/src/ExpressiveAnnotations.MvcWebSample/Views/Home/Home.cshtml#L153) function in particular.

In addition, to grab more outlook, go through similar questions which already have been asked before, i.e. https://github.com/jwaliszko/ExpressiveAnnotations/issues/121, and updated https://github.com/jwaliszko/ExpressiveAnnotations/issues/139.

**Comment by macfs36** [comment]
Thanks jwaliszko. I will take a look that.

**Comment by jwaliszko** [comment]
Related section added to the documentation: https://github.com/jwaliszko/ExpressiveAnnotations/tree/c01b93a3ed19aaae233edbcd2aea674ab2d80df6#can-i-decorate-conditionally-required-fields-with-asterisks
