### ISSUE TITLE
client-side ajax support

### ISSUE THREAD

**Issue by sync876** [jwaliszko/ExpressiveAnnotations#37]
Client side validation methods has a jquery ajax request to web service. The request is executed on every key up event (as the event happens) which is too frequent. How can I specify a delay mechanism?

**Comment by JaroslawWaliszko** [comment]
I'm currently browsing through some old issues, to verify the quality of my answers, and I'd like to apologize because I've noticed that I've misunderstood you, and provided incorrect answer to your question. The correct answer is following:

expressive.annotations.validate.js relays on jquery.validate.js and jquery.validate.unobtrusive.js internally. It's jquery.validate.js responsibility to trigger validation, and it is the source where you should look for reconfiguration of default behavior. In your case it could be like this:
```
<script>
    $(document).ready(function() {

        var validator = $('#yourForm').validate();
        validator.settings.onkeyup = function(element, event) {
            if (element.id === 'yourInput') {
                var that = this;
                setTimeout(function() {
                    that.element(element); // trigger validation after the delay
                }, 1000);
            } else { // otherwise, trigger default validation logic
                if (event.which === 9 && this.elementValue(element) === '') {
                    return;
                } else if (element.name in this.submitted || element === this.lastActive) {
                    this.element(element);
                }
            }
        }

    });
</script>
```

So it's the first thing - the delay. 

Now, when it comes to ajax requests inside methods registered in `expressive.annotations.validate.js`. It is not yet supported. Although there is an ongoing work on [async-work branch](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/tree/async-work), created especially for asynchronous-related ideas. Any help (either code reviews, testing or alternative ideas) is always highly appreciated.

Regards
