### ISSUE TITLE
Allow ability to extend client-side type-parsing (or natively support JSON fields)

### ISSUE THREAD

**Issue by ghost** [jwaliszko/ExpressiveAnnotations#38]
I'm sure this is by design but v2.3.0 no longer exposes the private API via the `___6BE7863DC1DB4AFAA61BB53FF97FE169` property so I guess this is more of an enhancement request than a bug.  

I am looking for support for JSON-serialized properties and/or support for extending the type parsing via a public API.

I have a model for which I want to compare a value to a list of values using `RequiredIfAttribute` and a custom `ListContains` method. 

``` csharp
public class BasicModel
    {
        public bool ListContains(int? value, IEnumerable<int> list)
        {
            return list != null && list.Contains(value.GetValueOrDefault());
        }

        [Required]
        public int? ReasonId { get; set; }

        [RequiredIf("ListContains(ReasonId, ReasonIdsRequiringOtherInfo)")]
        public string ReasonOther { get; set; }

        public IEnumerable<int> ReasonIdsRequiringOtherInfo { get; set; }
    }
```

`ReasonIdsRequiringOtherInfo` is rendered to the browser as a hidden input with the value as serialized JSON.

In the past I was able to inject support for serialized JSON data in fields into EA via the following script (which would also allow my `ListContains` method to work client-side):

``` javascript
(function ($, ea) {
    ea.addMethod("ListContains", function (value, list) {
        return $.inArray(value, list) >= 0;
    });

    // undocumented API - may break in future versions of Expressive Annotations
    var typeHelper = ea.___6BE7863DC1DB4AFAA61BB53FF97FE169.typeHelper;

    typeHelper.complex = {
        tryParse: function (value) {
            var result;

            try {
                result = JSON.parse(value);
            } catch(ex) {
                result = { error: true, msg: 'Given value was not recognized as valid JSON.' };
            }

            return result;
        }
    };

    var oldTryParse = typeHelper.tryParse;

    typeHelper.tryParse = function (value, type) {
        switch (type) {
            case 'complex':
                return typeHelper.complex.tryParse(value);
            default:
                return oldTryParse(value, type);
        }
    };
}(jQuery, window.ea));
```

This workaround also allowed me to keep the default expressive.annotations.validate.js file unchanged, which makes updating via NuGet much easier.  

If there is a better or alternative solution I would also be interested in that.

**Comment by JaroslawWaliszko** [comment]
For next version (2.6.0) I'm planning to modify the logic. Instead of `parseDate` and `parseObject` methods to be implemented, there will be only one method, mainly `parseValue` - to be overridden, e.g.:
```
<script>
    ea.settings.parseValue = function(value, type, defaultParseCallback) {
        switch (type) {
            case 'sometype': // handle value of this type on your own
                return ...
            default: // finally, for other types, do not forget...
                return defaultParseCallback(value, type); // ...to run the built-in logic
        }
    }
```
The advantage over current approach - parsing possibility will be given for any custom type (not only for `datetime` and generic `object` containing all non-simple types). I hope it will be more convenient.

**Comment by webwizgordon** [comment]
Sounds like a good approach as it is ultimately more flexible. It may be useful to have an optional way to specify a custom type from the C# model via an attribute [as I had mentioned previously in this thread](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/issues/38#issuecomment-64701374). 
  
Trying to handle `case 'object':` with multiple custom types could be messy otherwise.

That way you could have:
```csharp
public class MyModel
{
    [CustomType("json")]
    public MySubModel SubModel { get; set; }

    [CustomType("typeNeedingCustomParser")]
    public AMoreComplexObject MoreComplex { get; set; }
}
```  

```javascript
ea.settings.parseValue = function(value, type, defaultParseCallback) {
    switch (type) {
        case 'json':
            return ...
        case 'typeNeedingCustomParser':
            return ...
        default: // finally, for other types, do not forget...
            return defaultParseCallback(value, type); // ...to run the built-in logic
    }
}
```
`CustomType` might be too generic of a name though.  

And if no attribute is provided, then you could use your current type-detection logic.  
  
Another idea (combined with the above) could be to allow registration of "value parsers" instead of simply setting a function to the settings as it could allow for easier creation and consumption of libraries that depend on Expressive Annotations and require their own parsing logic as they wouldn't have to compete with each other or the consuming application overriding that method.  

Maybe something like:
```javascript
ea.settings.registerValueParser('typeNeedingCustomParser', function(value) {
   ...
}));
```

That way Library A could include its own script that registers value parser(s) for its custom type(s). Library B could include its own script to do the same as well. And the consuming application just needs to make sure those JavaScript files are referenced and can also implement its own parser(s) for its own custom type(s). I'm not sure what would/should happen if multiple parsers were registered for the same type.

I guess it's a similar concept to Model Binders in ASP.NET MVC.

**Comment by JaroslawWaliszko** [comment]
Thank you for help. 

I like your idea, I should have implemented that before. Previously I wanted to keep the code as simple as possible and thought that such flexibility would be excessive (probably majority of the users do not need it, IMO). But it is nice after all and actually someone indirectly [have asked for it](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/issues/65), so it will be done. 

One thing I'd like to change though. I mean `CustomType` attribute. I don't think it is needed that much. What I'd prefer is the automatic usage of the type name itself for parser name (short name - without namespace), e.g.
```
ea.settings.registerValueParser('sometype', function(value) { ...
```
It means less code and simplify stuff a bit though. I know that multiple types can use the same serialization method, but instead of decorating multiple c# types (or properties) with the same attribute, we can provide the possibility to enter multiple parser names at client-side, e.g.
```
ea.settings.registerValueParser('sometype1, sometype2, etc', function(value) { ...
```

**Comment by webwizgordon** [comment]
For `IEnumerable<int>`, would the type on the client side be ``'ienumerable`1[int]'`` or just `'ienumerable'` or similar?

The idea with the `[CustomType]` (maybe `[ParserType]` would be a better name) attribute would be that it is not required for most cases. If it's not present, you automatically infer the type name (short name) as you mention. If it is present, it takes precedence. There may be some properties declared as `object` or `dynamic` that might be serialized as JSON in Library A but require a custom parser in Library B and that could potentially create a conflict to register a parser for `'object'`.

Also, 
```javascript
ea.settings.registerValueParser('ienumerable`[int], ienumerable[string], myCustomClassSerializedAsJson, etc', function(value) {
```
might be more difficult to maintain as every time a property of a new type is added, you have to keep updating the registration to add the new type. With the attribute, you can just register a parser than can handle JSON,

```javascript
ea.settings.registerValueParser('json, etc.', function(value) {
```
and not have to keep updating it for each unique type.

I do agree that even with the above, it could still be useful to be able to register multiple types to a parser.

This is your library though, so I don't want to step on any toes.

**Comment by JaroslawWaliszko** [comment]
You may have a point here. For sure it is more straightforward for users since they're explicitly providing a name, it's not inferred somehow (if you're new user you don't really know until you'll debug through it). You're not stepping on any toes. It's valuable feedback for me, I wish to have more advices like that.

And (probably this question is silly but it confuses me), what do you think about naming, i.e. right now we have `ea.settings.dependencyTriggers` or `ea.settings.debug`, but at the same time `ea.addMethod()` or `ea.noConflict()` (see no `settings` in the last two). 

Because this change we are talking about is a breaking change anyway, maybe we can allow ourselves do more breaking changes at once and do some cleanups. In your opinion, it would be better to have:

`ea.addMethod()` or `ea.settings.addMethod()` or maybe `ea.registerMethod()` or finally `ea.settings.registerMethod()`

I'd like to be consistent with the value parser addition naming, so that decision automatically infers below option:

`ea.addValueParser()` vs `ea.settings.addValueParser()` vs `ea.registerValueParser()` vs `ea.settings.registerValueParser()`

When it comes to `ea.noConflict()` it is probably good one, since it is not related to **settings** at all.

The least invasive choice would be:
```
    api = {
        settings: {
            debug: false, // as before
            dependencyTriggers: 'change keyup' // as before
        },
        addMethod: function(name, func) { ... // as before
        addValueParser: function(type, func) { ... // new thing
        noConflict: function() { ... // as before
    }
```
but is it good?

**Comment by webwizgordon** [comment]
I think your least invasive sample is good. `addValueParser` is more consistent with `addMethod`. `addX` vs. `registerX` is simply a naming choice IMO. Consistency is important.

If you did want to switch to `registerMethod` you could keep `addMethod` as an deprecated alias and log a warning to the console when `addMethod` is called.  e.g.

```javascript
addMethod(name, func) {
    registerMethod(name, func);
    console.warn("ea.addMethod() is deprecated and may be removed in a future version. Use ea.registerMethod() instead");
}
```

On a related note, I'm not sure that either `addMethod` or `registerMethod` is very descriptive but I'm struggling to think of a better name.

I think it's fine that `addMethod`, `addValueParser`, and `noConflict` are outside of `settings`, as they aren't truly configuration settings but just API functions. It wouldn't make much sense to put the entire API under `settings`.

**Comment by JaroslawWaliszko** [comment]
Changeset pushed: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/4f44cb4f9f5736caf56e271e9bd342ac9e2eed6e.
