### ISSUE TITLE
Check if DateTime is not null or not the same as DateTime.MinValue with AssertThat throws error

### ISSUE THREAD

**Issue by senzacionale** [jwaliszko/ExpressiveAnnotations#95]
Works correct!

```javascript
[AssertThat("StartDate <= EndDate", ErrorMessage = Translations.Global.DATE_START_NOT_AFTER_DATE_END)]
```

ERROR:

```javascript
[AssertThat("StartDate <= EndDate && EndDate != null ", ErrorMessage = Translations.Global.DATE_START_NOT_AFTER_DATE_END)]

[AssertThat("StartDate <= EndDate && EndDate != DateTime.MinValue", ErrorMessage = Translations.Global.DATE_START_NOT_AFTER_DATE_END)]
```

throws error: Exception has been throws by target of an invocation

It is not possible to check if DateTime is null or not the same as DateTime.Minvalue?

**Comment by jwaliszko** [comment]
All these behaviors are by design.

Regarding "error" cases:

1. Comparison operators cannot be applied to operands of non-nullable value type and 'null' literal.
 
 The exception message which have been thrown says:
 ```
 Parse error on line xx, column yy:
 ... != null ...
      ^--- Operator '!=' cannot be applied to operands of type 'System.DateTime' and 'null'.
 ```
 To fix it, `EndDate` should be of nullable type, i.e. `DateTime?`.

2. Accessing properties from outside of the model scope is not implemented. Properties you want to use in expressions must be public, explicitly available in your model context, and later (unless constants and enum identifiers) exposed in the view.

 The exception message which have been thrown says:
 ```
 Parse error on line xx, column yy:
... DateTime.MinValue ...
        ^--- Only public properties, constants and enums are accepted. Identifier 'DateTime.MinValue' not 
known. 
```
 The solution is either:

 * enrich your model with `MinDate` property:

   ```
   public DateTime MinDate
   {
            get { return DateTime.MinValue; }
   }
   ```
   and expose it in the view for client-side:

      ```
       @Html.HiddenFor(m => m.MinDate)
   ```
 * or, enrich your model with `MinDate()` method:

      ```
  public DateTime MinDate() 
  {
          return DateTime.MinValue;
  }
  ```
  and provide its client-side equivalent:

      ```
  <script>    
          ea.addMethod('MinDate', function() {
              return new Date(...).getTime(); // return milliseconds
          });
  ```

**Comment by senzacionale** [comment]
jwaliszko thank you for explanation!
