### ISSUE TITLE
No more than 27 unique attributes of the same type can be applied for a single field or property.

### ISSUE THREAD

**Issue by senzacionale** [jwaliszko/ExpressiveAnnotations#96]
```javascript
<td class="center">
            @Html.ValidationMessageFor(modelItem => Model.StudentsWorksReportsFormModel.StudentWorkReportViewModelList[i].StudentWorkReportFormModel.StartDate)
            <div class="input-append date" id="@Html.RenderNumbers("StartDatePickerComponent", i)">
                @Html.TextBoxFor(modelItem => Model.StudentsWorksReportsFormModel.StudentWorkReportViewModelList[i].StudentWorkReportFormModel.StartDate,
                    new
                    {
                        @Value = Model.StudentsWorksReportsFormModel.StudentWorkReportViewModelList[i].StudentWorkReportFormModel.StartDate != DateTime.MinValue ? Model.StudentsWorksReportsFormModel.StudentWorkReportViewModelList[i].StudentWorkReportFormModel.StartDate.ToString("d") : "",
                        id = @Html.RenderNumbers("StartDate", i),
                        @readonly = "readonly",
                        @class = "input-small focused"
                    })
                <span class="add-on"><i class="icon-th"></i></span>
            </div>
        </td>
```

it is looped 100 times, so 100 customers:

and there is a AssertThat in model:
```javascript
[AssertThat("StartDate <= EndDate", 1, ErrorMessage = Translations.Global.DATE_START_NOT_AFTER_DATE_END)]
```

which throws and exception:
No more than 27 unique attributes of the same type can be applied for a single field or property.

why is this not allowed?

Can you make this method public?

```javascript
private void AssertAttribsQuantityAllowed(int count)
        {
            const int max = 27;
            if (count > max)
                throw new InvalidOperationException(
                    $"No more than {max} unique attributes of the same type can be applied for a single field or property.");
        }
```

**Comment by jwaliszko** [comment]
There is a protection against following usage case:
```
[AssertThat("expression 0")]
[AssertThat("expression 1")]
...
[AssertThat("expression N")]
public string Field { get; set; }
```
when N > 26. 

I explicitly restricted the number of unique attributes of the same type which can be applied to a single property to 27. If counter is exceeded, exception is thrown. 

This issue is a side effect of this assertion.

Restriction has been introduced after I encountered a puzzle, of how to register exact number of adapters for client-side component of EA. 

To be more precise, when attribute is applied to some model field, corresponding validation adapter is created and related with such a field at client-side, i.e. `$.validator.unobtrusive.adapters.add(name, ...` Unfortunately I haven't found a way to register exact numbers of adapters in JavaScript. I can easily count the number of attributes at server-side, but how to inform JavaScript how much of them we have? It would be ideal to have exactly as many adapters as there are unique annotations, but the number of annotations isn't known untill DOM is ready.

Due to that, each field has exactly 27 adapters assigned, with hardcoded unique names, e.g. `assertthat, assertthata, asserthatb, ..., assertthatz`. 27 is just a number which seemed not too high for me to have redundant handlers (most of the time 27 is too much anyway) and... it was easy to generate unique names using all the letters of latin alphabet. 

For more details please see [expressive.annotations.validate.js](https://raw.githubusercontent.com/jwaliszko/ExpressiveAnnotations/f0d79d6166d65ad2fae403ccca41ff2e83d105df/src/expressive.annotations.validate.js) sources and logic related with `annotations = ' abcdefghijklmnopqrstuvwxyz';` line.

Any ideas solving this problem correctly are very welcome.

**Comment by rwil02** [comment]
Html.TextBoxFor and the like generate an ID / name based on a prefix built from a 'stack' of container names in order to be unique by 'instance' right?

Is there any way for you to access that unique prefix in the right place to pass it to the adapters.add?

**Comment by senzacionale** [comment]
```javascript
annotations = ' abcdefghijklmnopqrstuvwxyz'; // suffixes for attributes annotating single field multiple times
```

Why not to use combinations of them?

Like: assertthatab, assertthatudm...

**Comment by jwaliszko** [comment]
@senzacionale: it would be a huge waste of JavaScript memory. Having e.g. 100 adapters created always for each field, while only one or to are used most of the time, is not an option. And then, what if instead of 100, 200 adapters are required for some specific case? The only solution is to provide exact numbers of them for each field i.e. as many as there are corresponding annotations.

**Comment by senzacionale** [comment]
@jwaliszko I know that my Model "SatrtDate" list count is 100, because I have a loop and I know exact number.

can I do something with this?

**Comment by jwaliszko** [comment]
@rwil02: I don't understand how it could have helped when it comes to registration of appropriate number of adapters.

**Comment by jwaliszko** [comment]
@senzacionale: Unfortunately currently I don't know any other than fork and custom code change.

**Comment by senzacionale** [comment]
Can you give me some hints how to check the numbers and loop?

**Comment by jwaliszko** [comment]
@senzacionale: I refer you to this source: http://stackoverflow.com/q/25414296/270315, where I've described my thinking of how current implementation has been initially done. There has been some refactoring since that time, but the basic conception hasn't changed. It will give you more complete outlook of the design.

In short, you should modify `AllocateSuffix()` method to allocate as many unique suffixes as you need - each suffix guarantees unique validation type name (adapter name). The same suffixes need to be provided at client-side - again all logic related to this line: `annotations = ' abcdefghijklmnopqrstuvwxyz';` should be adjusted (including this line itself). Take under consideration that the validation types names are enforced by MVC framework to consist only with lowercase letters for some reason.

Keep in mind that it is extremely rough workaround which has nothing in common with a desired solution.

**Comment by jwaliszko** [comment]
If anyone is interested of how to simply reproduce this particular issue using [MvcWebSample](https://github.com/jwaliszko/ExpressiveAnnotations/tree/master/src/ExpressiveAnnotations.MvcWebSample) project, go to [Contact.cs](https://raw.githubusercontent.com/jwaliszko/ExpressiveAnnotations/67fdc42777a2d0e2c9e11e2b569cb75febd1787d/src/ExpressiveAnnotations.MvcWebSample/Models/Contact.cs) model class and replace this line:
```
Addresses = new List<Address> { new Address { Type = Resources.HomeAddress }, new Address { Type = Resources.OfficeAddress } };
```
with this one:
```
Addresses = Enumerable.Range(0, 28).Select(x => new Address { Type = Resources.HomeAddress } ).ToList();
```

**Comment by rwil02** [comment]
Well, at the moment, you basically have (e.g.)
2 fields, a,& b repeated multiple times
Let's say A has 'Assert that a > b' and b has 'Assert that b != null'
If you have 100 items, you get 100 of each
But those 100 items are rendered as
X1_A, X1_B
X2_A, X2_B
etc

so really you have something like
List['X1'] = {a, b, AssertThatA, AssertThatB}  where a = X1_A and b = X1_b
List['X2'] = {a, b, AssertThatA, AssertThatB}  where a = X2_A and b = X2_b

and not 
a, b, AssertThatA, AssertThatB where a = X1_A and b = X1_b
a, b, AssertThatC, AssertThatD where a = X2_A and b = X2_b


And that X1, X2 etc are related to calls to something like PrefixScope or StartItem?

**Comment by jwaliszko** [comment]
@senzacionale, @rwil02: I still do not know how to register the exact numbers of adapters, but at least the side effect related to this particular issue is solved here: https://github.com/jwaliszko/ExpressiveAnnotations/commit/ad078cccc63ca1d83464d55fd913a9dd44999907.

**Comment by senzacionale** [comment]
I just don't understand how for example jquery required method works for all properties?

**Comment by jwaliszko** [comment]
v2.6.6 [released](https://github.com/jwaliszko/ExpressiveAnnotations/releases/tag/v2.6.6)

**Comment by senzacionale** [comment]
Thank you for fast fix.

**Comment by jwaliszko** [comment]
@senzacionale: you're welcome, thanks for reporting this problem.

**Comment by izakbar** [comment]
If I have array of data fields and each is same type and name - just array index is different, then EA treats them all as same for purpose of the count > 27 check. It can very quickly get to >27 assertions.
If I have 8 instances of the data item on the form and there are 4 x asserts on the field.. I get count of 32. boom EA says no because it sees each array index as same field. I can understand not wanting 100s of adaptors on each field, but these are seperate instances of the field - but ea sees them as the same (I think). Either having the array index as part of the AttributeWeakId would fix or allowing >27 at users risk.

_Simple workaround to allow more than 27 that I have currently implemented locally is to use count.ToString("X2").ToLowerVariant(); instead of char.ConvertFromUtf32(95+ count); - and changed const int max = 27 to const int max = 64_   -- this is rubbish - doesnt work in js side :(

Okay, what I have found is that if I pass the context.Attributes["id"] as extra parameter to RequireIfValidator and AssertValidator and then in ExpressiveValidator instead of using metadata.PropertyName - use the passed id (if not null and length>0) otherwise use metadata.PropertyName. This seems to work nicely as now each instance of the data only has the 4 asserts :) and they are assert asserta b c - and more importantly they fire ! - and ofc this I did in the .net core fork version.. which doesn't translate super well to this version. Oh joy.
